name: Deploy Next.js site to Pages

on:
  # Automatic deployment for main branch
  push:
    branches:
      - main
      - feature/*
      - theme/*
  # Manual trigger for any branch
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      # Set branch-specific base path
      - name: Set branch path
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BRANCH="${{ github.event.inputs.branch }}"
            echo "NEXT_PUBLIC_BASE_PATH=/phaser-new-maps/branches/${BRANCH//\//-}" >> $GITHUB_ENV
          else
            echo "NEXT_PUBLIC_BASE_PATH=/phaser-new-maps" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: bun install

      - name: Build with Next.js
        run: bun run build

      # Create branch-specific directory for non-main deployments
      - name: Prepare deployment directory
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BRANCH="${{ github.event.inputs.branch }}"
            mkdir -p "./branches/${BRANCH//\//-}"
            mv out/* "./branches/${BRANCH//\//-}/"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.event_name == 'workflow_dispatch' && './branches' || './out' }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
