name: Deploy PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Build steps remain same until deployment
      - name: Set PR path
        run: |
          echo "NEXT_PUBLIC_BASE_PATH=/phaser-new-maps/pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Build with Next.js
        run: bun run build

      # Deploy to a PR-specific branch
      - name: Deploy PR preview
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b pr-preview-${{ github.event.pull_request.number }}
          cp -r out/* .
          git add .
          git commit -m "Deploy PR #${{ github.event.pull_request.number }} preview"
          git push -f origin pr-preview-${{ github.event.pull_request.number }}
